---
- name: SST_OPS_TA
  hosts: "{{ ansible_env.DEPLOY_TARGET }}"
  gather_facts: false
  tasks:
    - name: Copy compose file to target machine
      copy:
        src: "{{ COMPOSE_FILE_PATH }}"
        dest: "/tmp/{{ COMPOSE_FILE_PATH | basename }}"
        remote_src: yes

    - name: Deploy Swarm stack and check status
      ansible.builtin.docker_swarm_stack:
        name: "{{ STACK_NAME}}"
        compose_file: "{{ COMPOSE_FILE_PATH | basename }}"
        state: present
      register: deploy_output
